"""UI sizing, spacing, and non-color visual tuning settings."""

# Window and layout
APP_WINDOW_WIDTH = 1360
APP_WINDOW_HEIGHT = 760
APP_WINDOW_MIN_WIDTH = 1260
APP_WINDOW_MIN_HEIGHT = 700
WINDOW_START_MAXIMIZED = True
APP_ROOT_MARGIN = 12
APP_ROOT_SPACING = 12
SPLITTER_HANDLE_WIDTH = 10
SIDE_PANEL_WIDTH = 340
MIN_VIDEO_PANEL_WIDTH = 500
CONTROL_BUTTON_HEIGHT = 38
CARD_MARGIN = 12
CARD_SPACING = 10
VIDEO_STAGE_SPACING = 8
HEADER_MARGIN = 18
HEADER_SPACING = 4
SCROLLBAR_VIEWPORT_MARGIN = 8
SIDE_PANEL_CONTENT_RIGHT_MARGIN = 10
SIDE_PANEL_SECTION_SPACING = 12
OVERVIEW_HORIZONTAL_SPACING = 8
OVERVIEW_VERTICAL_SPACING = 6
RESULT_TABLE_MIN_HEIGHT = 260

# Video canvas
VIDEO_CANVAS_MIN_WIDTH = 460
VIDEO_CANVAS_MIN_HEIGHT = 320

# History drawer
HISTORY_DRAWER_COLLAPSED_WIDTH = 40
HISTORY_DRAWER_EXPANDED_WIDTH = 360
HISTORY_ACTION_BUTTON_HEIGHT = 28
HISTORY_LAYOUT_SPACING = 8
HISTORY_BODY_MARGIN = 8
HISTORY_HEADER_MARGIN = 2
HISTORY_LIST_RIGHT_MARGIN = 10
HISTORY_EMPTY_VERTICAL_MARGIN = 16
HISTORY_CARD_SPACING = 6

# Toggle switch
TOGGLE_SWITCH_WIDTH = 64
TOGGLE_SWITCH_HEIGHT = 30
TOGGLE_SWITCH_BORDER_WIDTH = 1.5
TOGGLE_SWITCH_LABEL_PIXEL_SIZE = 10
TOGGLE_SWITCH_ON_LABEL = "ON"
TOGGLE_SWITCH_OFF_LABEL = "OFF"

# Overlay and drawing
UI_TARGET_WIDTH = 800
UI_TARGET_HEIGHT = 600
LINE_OVERLAY_ALPHA = 0.1
LINE_THICKNESS = 2
UI_BASE_ARROW_LEN = 50
UI_BASE_FONT_SCALE = 0.7
OVERLAY_LABEL_FONT_SCALE_COMPACT = 0.34
OVERLAY_LABEL_FONT_SCALE_SMALL = 0.40
OVERLAY_LABEL_FONT_SCALE_MEDIUM = 0.48
OVERLAY_LABEL_FONT_SCALE_LARGE = 0.56
OVERLAY_BOX_THICKNESS_SMALL = 1
OVERLAY_BOX_THICKNESS_LARGE = 2
OVERLAY_LABEL_PAD_X_COMPACT = 2
OVERLAY_LABEL_PAD_X_DEFAULT = 4
OVERLAY_LABEL_PAD_Y_COMPACT = 1
OVERLAY_LABEL_PAD_Y_DEFAULT = 2
OVERLAY_FONT_THICKNESS = 1
